[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.33"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "forge-std/=node_modules/forge-std/src/"
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1024
depth = 128
fail_on_revert = true
